services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - APP_PORT=${APP_PORT}
    container_name: sigma-frontend-dev
    image: sigma-frontend-dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - HOST_API=${HOST_API}
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
    networks:
      - sigma-network

networks:
  sigma-network:
    external: true
    name: sigma-network
