services:
  app:
    build:
      context: .
      target: runner
      args:
        - APP_PORT=${APP_PORT}
    container_name: sigma-frontend-prod
    image: sigma-frontend-prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - HOST_API=${HOST_API}
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
    networks:
      - sigma-network

networks:
  sigma-network:
    driver: bridge
    name: sigma-network
